version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Password1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_container_data:/var/lib/postgresql/data
    entrypoint: ["sh", "-c", "docker-entrypoint.sh postgres & sleep 10 & pg_restore -U postgres -d postgres /var/lib/postgresql/data/postgres_dump.sql"]
