version: '3.8'
services:
  postgres:
    image: postgres
    container_name: event_db
    environment:
      POSTGRES_PASSWORD: Password1
      POSTGRES_USER: postgres
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./event_db.sql:/docker-entrypoint-initdb.d/event_db.sql

volumes:
  postgres_data: